---
version: '3.1'
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    # user: 1001:1001
    # secrets: 
    #   - portainer-admin-pw
    environment:
      # - UID=1001
      # - GID=1001
      - TZ=Australia/Melbourne
      - VIRTUAL_HOST=por.fet.fit,pt.fet.fit,p.fet.fit,port.fet.fit,portainer.fet.fit
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=por.fet.fit,pt.fet.fit,p.fet.fit,port.fet.fit,portainer.fet.fit
    # command: --admin-password-file /run/secrets/portainer-admin-pw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config:/data
      # - ./config-portainer:/data
      # - /path/to/your/certs:/certs
    networks: 
        - "docker-proxy"
    ports:
      - 8000:8000
      # - 9000:9000
      # - 9443:9443
    restart: always

networks:
  docker-proxy:
    external: true
volumes:
  config:


# docker network create net
# https://linuxhandbook.com/nginx-reverse-proxy-docker/
