---
version: '3.1'
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    # secrets: 
    #   - portainer-admin-pw
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Australia/Melbourne
    # command: --admin-password-file /run/secrets/portainer-admin-pw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/data
    ports:
      - 9000:9000
    restart: always

  agent:
    container_name: portainer-agent
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    restart: always
# secrets:
#   portainer-admin-pw:
#     file: ./secrets/admin-pw
#     # external: true

