---
services:
  portainer-server:
    image: portainer/portainer-${PORTAINER_EDITION}:${PORTAINER_VERSION}
    container_name: portainer_server
    profiles: ["host"]
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9000:9000
    env_file:
      - ".portainer.env"
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/portainer_${PORTAINER_EDITION}:/data
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.$${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer-server.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.service=portainer-server"
      - "traefik.http.routers.portainer.tls.certresolver=${CERT_RESOLVER}"

  dozzle-hub:
    image: amir20/dozzle:latest
    container_name: dozzle_hub
    profiles: ["host"]
    restart: unless-stopped
    environment:
      DOZZLE_AUTH_PROVIDER: simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/dozzle:/data
    ports:
      - 9999:8080
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.$${DOMAIN_NAME`)"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.services.dozzle-hub.loadbalancer.server.port=8080"
      - "traefik.http.routers.dozzle.service=dozzle-hub"
      - "traefik.http.routers.dozzle.tls.certresolver=${CERT_RESOLVER}"

  portainer-edge-agent:
    image: portainer/agent:${PORTAINER_VERSION}
    container_name: portainer_edge_agent
    profiles: ["agent"]
    restart: unless-stopped
    env_file:
      - .portainer.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host:ro
      - ./config/portainer_agent_data:/data

  dozzle-agent:
    image: "amir20/dozzle:latest"
    container_name: dozzle_agent
    profiles: ["agent"]
    restart: unless-stopped
    command: agent
    environment:
      - DOZZLE_LEVEL=info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${BIND_ADDRESS}:7007:7007"
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s

networks:
  web:
    external: true
