---
version: '3.1'
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    env_file:
      - "../env/ace.env"
    environment:
      - TZ=Australia/Melbourne
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config:/data
    networks: 
        - "docker-proxy"
    ports:
      - 8000:8000
      - 9000:9000
    restart: always

networks:
  docker-proxy:
    external: true
volumes:
  config:
