---
version: '3.1'
services:
  portainer:
    extends:
      file: docker-compose.yml
      service: portainer

    environment:
      - VIRTUAL_HOST=pt.${PROXY_DOMAIN},portainer.${PROXY_DOMAIN}
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=pt.${PROXY_DOMAIN},portainer.${PROXY_DOMAIN}

    networks: 
      - "docker-proxy"

networks:
  docker-proxy:
    external: true

volumes:
  config:
