#! /bin/bash

export HOSTNAME

if [[ ! -z `docker compose version 2>/dev/null` ]]; then
  docker compose --env-file "../env/$HOSTNAME.env" down
  docker compose --env-file "../env/$HOSTNAME.env" up -d
else
  docker-compose --env-file "../env/$HOSTNAME.env" down
  docker-compose --env-file "../env/$HOSTNAME.env" up -d
fi

